from odoo.addons.mis_builder.models.kpimatrix import KpiMatrix

# Monkeypatch KpiMatrix.as_dict to include css_class from the style
original_as_dict = KpiMatrix.as_dict

def as_dict_with_css_class(self):
    res = original_as_dict(self)
    
    # Iterate through rows and inject css_class if available
    for row_data in res.get('body', []):
        # We need to find the corresponding KpiMatrixRow to get the style
        # The row_data has a 'row_id' but it might be constructed complexly.
        # However, KpiMatrix.as_dict iterates self.iter_rows().
        # Let's see if we can easily map it. 
        # Actually, KpiMatrix.as_dict iterates self.iter_rows() and builds the list.
        # We can't easily map back from the listed dicts to the objects without re-iterating.
        pass
    
    # Re-implementation of as_dict to include css_class
    # This is safer than trying to patch the result
    res = {
        'header': [],
        'body': [],
        'notes': self.get_notes_by_cell_id()
    }
    
    # Header construction (same as original)
    for col in self.iter_cols():
        col_data = {'label': col.label, 'description': col.description, 'cols': []}
        for subcol in col.iter_subcols():
            col_data['cols'].append({
                'label': subcol.label,
                'description': subcol.description,
                'colspan': 1,
            })
        if col_data['cols']:
            # Adjust colspan for the first empty subcol generated by mis_builder
            # effectively ignoring the first subcol if it's empty/spacer?
            # actually mis_builder's as_dict logic is:
            # list(col.iter_subcols())[1:] for the colspan
            # Let's inspect the original implementation to be exact.
            pass

    # COMPLETE RE-IMPLEMENTATION OF as_dict
    # To avoid brittleness, we will iterate the rows again and match by index?
    # No, iteration order is deterministic.
    
    body = []
    for row in self.iter_rows():
        if row.style_props.hide_always or (row.style_props.hide_empty and row.is_empty()):
            continue
            
        row_data = {
            'label': row.label,
            'description': row.description,
            'style': self.style_model.to_css_style(row.style_props),
            'css_class': row.style_props.get('css_class', ''), # INJECTION HERE
            'cells': [],
        }
        
        for cell in row.iter_cells():
            cell_data = {
                'val_r': cell.val_rendered,
                'val_c': cell.val_comment,
                'style': self.style_model.to_css_style(cell.style_props),
                'css_class': cell.style_props.get('css_class', ''), # INJECTION HERE
                'cell_id': cell.cell_id,
            }
            if cell.drilldown_arg:
                cell_data['drilldown_arg'] = cell.drilldown_arg
            # Add annotation logic if needed, but original uses widget logic for that?
            # Check original code...
            # Original code adds 'can_be_annotated'
            # cell_data['can_be_annotated'] = ...
            # This is getting complicated to re-implement perfectly.
            
            # BETTER STRATEGY: 
            # 1. Call original as_dict
            # 2. Iterate self.iter_rows() again, filter out hidden rows (same logic)
            # 3. Zip the result body with the visible rows and update.
            pass
            
    return res

def as_dict_patched(self):
    res = original_as_dict(self)
    
    # Generator for visible rows to match the output body
    def visible_rows():
        for row in self.iter_rows():
            if not (row.style_props.hide_always or (row.style_props.hide_empty and row.is_empty())):
                yield row

    # Inject css_class
    body_rows = res.get('body', [])
    vis_rows = visible_rows()
    
    for i, row_data in enumerate(body_rows):
        try:
            kpi_row = next(vis_rows)
            # Inject the class from style_props
            css_class = kpi_row.style_props.get('css_class') or ''
            
            # Generic Subtotal Detection Heuristic
            # If it's a summary row (no account_id) and looks like a computed formula (no '['),
            # treat it as a subtotal line.
            is_computed_subtotal = False
            if not kpi_row.account_id and kpi_row.kpi and kpi_row.kpi.expression:
                # Expressions with '[' usually imply data extraction (e.g. balp[...])
                # Expressions without '[' are usually formulas (e.g. revenue - cogs)
                if '[' not in kpi_row.kpi.expression:
                    is_computed_subtotal = True
            
            if is_computed_subtotal:
                css_class = (css_class + ' mis_subtotal_line').strip()

            if css_class:
                row_data['css_class'] = css_class
        except StopIteration:
            break
            
    return res

KpiMatrix.as_dict = as_dict_patched
